Repository APPJAM-Roughly-deciding/APPJAM-Backend, pull requests merged in 2021-12, with the labels that each got.

#2 🔀 :: (#1) 유저 엔티티 설정
  src/main/java/com/example/appjambackend/domain/user/entity/User.java
  src/main/java/com/example/appjambackend/domain/user/entity/UserRepository.java
  src/main/java/com/example/appjambackend/domain/user/presentation/UserController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 기능 추가, 프로젝트 설정

#4 🔀 :: (#3) 시큐리티 기본 설정
  build.gradle
  src/main/java/com/example/appjambackend/AppjamBackendApplication.java
  src/main/java/com/example/appjambackend/global/security/SecurityConfig.java
  src/main/java/com/example/appjambackend/global/security/details/CustomUserDetails.java
  src/main/java/com/example/appjambackend/global/security/details/CustomUserDetailsService.java
  src/main/java/com/example/appjambackend/global/security/jwt/JwtProperties.java
  src/main/java/com/example/appjambackend/global/security/jwt/jwtProvider.java
  src/main/resources/application.yml
Labels: 기능 추가

#6 🔀 :: (#5) 회원가입
  src/main/java/com/example/appjambackend/domain/user/entity/User.java
  src/main/java/com/example/appjambackend/domain/user/entity/UserRepository.java
  src/main/java/com/example/appjambackend/domain/user/presentation/UserController.java
  src/main/java/com/example/appjambackend/domain/user/presentation/dto/request/SignUpRequest.java
  src/main/java/com/example/appjambackend/domain/user/service/SignUpService.java
Labels: 기능 추가

#12 🔀 :: (#11) ErrorCode 및 FeedService 약간
  src/main/java/com/example/appjambackend/domain/feed/entity/repository/FeedRepository.java
  src/main/java/com/example/appjambackend/domain/feed/facade/FeedFacade.java
  src/main/java/com/example/appjambackend/domain/feed/service/FeedService.java
  src/main/java/com/example/appjambackend/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/example/appjambackend/global/error/ErrorResponse.java
  src/main/java/com/example/appjambackend/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/appjambackend/global/error/exception/CustomExceptoin.java
  src/main/java/com/example/appjambackend/global/error/exception/ErrorCode.java
Labels: 기능 추가, 프로젝트 설정

#13 🔀 :: (#10) 시큐리티 필터
  src/main/java/com/example/appjambackend/global/security/SecurityConfig.java
  src/main/java/com/example/appjambackend/global/security/jwt/FilterConfig.java
  src/main/java/com/example/appjambackend/global/security/jwt/JwtFilter.java
  src/main/java/com/example/appjambackend/global/security/jwt/JwtProvider.java
Labels: 기능 추가

#16 🔀 :: (#14) 에러처리
  src/main/java/com/example/appjambackend/domain/user/exception/UserNotFoundException.java
  src/main/java/com/example/appjambackend/domain/user/service/SignInService.java
  src/main/java/com/example/appjambackend/domain/user/service/SignUpService.java
  src/main/java/com/example/appjambackend/global/error/exception/ErrorCode.java
  src/main/java/com/example/appjambackend/global/security/exception/ExpiredTokenException.java
  src/main/java/com/example/appjambackend/global/security/exception/InvalidTokenException.java
  src/main/java/com/example/appjambackend/global/security/jwt/JwtProvider.java
Labels: 기능 추가

#15 🔀 :: (#8) 게시물 API
  src/main/java/com/example/appjambackend/domain/feed/entity/Feed.java
  src/main/java/com/example/appjambackend/domain/feed/exceptoin/FeedNotFoundException.java
  src/main/java/com/example/appjambackend/domain/feed/facade/FeedFacade.java
  src/main/java/com/example/appjambackend/domain/feed/service/FeedServiceImpl.java
Labels: 기능 추가

#17 🔀 :: (#14) 에러처리
  src/main/java/com/example/appjambackend/global/error/ErrorResponse.java
  src/main/java/com/example/appjambackend/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/appjambackend/global/security/details/CustomUserDetailsService.java
  src/main/java/com/example/appjambackend/global/security/jwt/FilterConfig.java
  src/main/java/com/example/appjambackend/global/security/jwt/JwtExceptionFilter.java
  src/main/java/com/example/appjambackend/global/security/jwt/JwtProvider.java
Labels: 기능 추가, 리펙토링

#20 🔀 :: (#14) 에러처리(전처리)
  src/main/java/com/example/appjambackend/domain/user/presentation/UserController.java
  src/main/java/com/example/appjambackend/domain/user/presentation/dto/request/SignInRequest.java
  src/main/java/com/example/appjambackend/domain/user/presentation/dto/request/SignUpRequest.java
  src/main/java/com/example/appjambackend/global/error/GlobalExceptionHandler.java
Labels: 기능 추가

#21 🔀 :: (#14) 유저 에러처리
  src/main/java/com/example/appjambackend/domain/user/exception/UseridAlreadyExistException.java
  src/main/java/com/example/appjambackend/domain/user/facade/UserFacade.java
  src/main/java/com/example/appjambackend/domain/user/service/SignUpService.java
  src/main/java/com/example/appjambackend/global/error/exception/ErrorCode.java
Labels: 기능 추가

#23 🔀 :: (#22) 토큰재발급
  src/main/java/com/example/appjambackend/domain/user/entity/refresh/RefreshToken.java
  src/main/java/com/example/appjambackend/domain/user/entity/refresh/RefreshTokenRepository.java
  src/main/java/com/example/appjambackend/domain/user/presentation/UserController.java
  src/main/java/com/example/appjambackend/domain/user/service/TokenRefreshService.java
  src/main/java/com/example/appjambackend/global/security/jwt/JwtProvider.java
Labels: 기능 추가

#19 🔀 :: (#18) 이미지 업로드
  build.gradle
  src/main/java/com/example/appjambackend/domain/feed/entity/FeedMedium.java
  src/main/java/com/example/appjambackend/domain/feed/entity/FeedMediumRepository.java
  src/main/java/com/example/appjambackend/domain/feed/entity/FeedRepository.java
  src/main/java/com/example/appjambackend/domain/feed/exceptoin/FeedNotFoundException.java
  src/main/java/com/example/appjambackend/domain/feed/facade/FeedFacade.java
  src/main/java/com/example/appjambackend/domain/feed/presentation/FeedController.java
  src/main/java/com/example/appjambackend/domain/feed/presentation/dto/requset/ModifyFeedRequest.java
  src/main/java/com/example/appjambackend/domain/feed/presentation/dto/requset/PostFeedRequest.java
  src/main/java/com/example/appjambackend/domain/feed/presentation/dto/response/DefaultFeedResponse.java
  src/main/java/com/example/appjambackend/domain/feed/presentation/dto/response/PostFeedResponse.java
  src/main/java/com/example/appjambackend/domain/feed/service/FeedService.java
  src/main/java/com/example/appjambackend/domain/feed/service/FeedServiceImpl.java
  src/main/java/com/example/appjambackend/global/config/S3Config.java
  src/main/java/com/example/appjambackend/global/error/exception/ErrorCode.java
  src/main/java/com/example/appjambackend/global/security/exception/FileEmptyException.java
  src/main/java/com/example/appjambackend/global/security/exception/FileUploadFailException.java
  src/main/java/com/example/appjambackend/global/security/exception/TooManyFilesException.java
  src/main/java/com/example/appjambackend/global/util/s3/S3Service.java
  src/main/resources/application.yml
Labels: 기능 추가

#25 🔀 :: (#24) 댓글
  src/main/java/com/example/appjambackend/domain/comment/entity/Comment.java
  src/main/java/com/example/appjambackend/domain/comment/entity/CommentRepository.java
  src/main/java/com/example/appjambackend/domain/comment/presentation/CommentController.java
  src/main/java/com/example/appjambackend/domain/comment/service/PostCommentService.java
  src/main/java/com/example/appjambackend/domain/feed/entity/Feed.java
  src/main/java/com/example/appjambackend/domain/user/facade/UserFacade.java
  src/main/java/com/example/appjambackend/global/util/user/UserUtil.java
Labels: 기능 추가

#27 🔀 :: (#26) 댓글 삭제
  src/main/java/com/example/appjambackend/AppjamBackendApplication.java
  src/main/java/com/example/appjambackend/domain/comment/presentation/CommentController.java
  src/main/java/com/example/appjambackend/domain/comment/service/RemoveCommentService.java
  src/main/java/com/example/appjambackend/global/security/SecurityConfig.java
Labels: 기능 추가, 버그

#31 🔀 :: (#30) 북마크
  src/main/java/com/example/appjambackend/domain/comment/entity/Comment.java
  src/main/java/com/example/appjambackend/domain/comment/service/PostCommentService.java
  src/main/java/com/example/appjambackend/domain/mark/entity/Mark.java
  src/main/java/com/example/appjambackend/domain/mark/entity/MarkRepository.java
  src/main/java/com/example/appjambackend/domain/mark/presentation/MarkController.java
  src/main/java/com/example/appjambackend/domain/mark/service/PostMarkService.java
  src/main/java/com/example/appjambackend/domain/mark/service/RemoveMarkService.java
  src/main/java/com/example/appjambackend/domain/user/entity/User.java
  src/main/java/com/example/appjambackend/domain/user/facade/UserFacade.java
Labels: 기능 추가

#33 🔀 :: (#32) 좋아요
  src/main/java/com/example/appjambackend/domain/like/entity/Like.java
  src/main/java/com/example/appjambackend/domain/like/entity/LikeRepository.java
  src/main/java/com/example/appjambackend/domain/like/presentation/LikeController.java
  src/main/java/com/example/appjambackend/domain/like/service/PostLikeService.java
  src/main/java/com/example/appjambackend/domain/like/service/RemoveLikeService.java
  src/main/java/com/example/appjambackend/domain/mark/service/RemoveMarkService.java
  src/main/resources/application.yml
Labels: 기능 추가

#34 🔀 :: 도커 파일 및 주석 처리
  Docker-Compose.yml
  Dockerfile
  src/main/java/com/example/appjambackend/domain/feed/entity/FeedMedium.java
  src/main/java/com/example/appjambackend/domain/feed/entity/FeedRepository.java
  src/main/java/com/example/appjambackend/domain/image/entity/Image.java
  src/main/java/com/example/appjambackend/domain/image/entity/ImageRepository.java
  src/main/java/com/example/appjambackend/domain/image/facade/ImageFacade.java
  src/main/java/com/example/appjambackend/global/util/s3/S3Service.java
Labels: chore

#36 🔀 :: (#35) 이미지 + 마이페이지
  src/main/java/com/example/appjambackend/domain/feed/entity/Feed.java
  src/main/java/com/example/appjambackend/domain/feed/presentation/FeedController.java
  src/main/java/com/example/appjambackend/domain/feed/service/PostFeedService.java
  src/main/java/com/example/appjambackend/domain/image/entity/ImageRepository.java
  src/main/java/com/example/appjambackend/domain/image/exception/ImageNotFoundException.java
  src/main/java/com/example/appjambackend/domain/image/facade/ImageFacade.java
  src/main/java/com/example/appjambackend/domain/like/entity/LikeRepository.java
  src/main/java/com/example/appjambackend/domain/mark/entity/MarkRepository.java
  src/main/java/com/example/appjambackend/domain/user/presentation/UserController.java
  src/main/java/com/example/appjambackend/domain/user/presentation/dto/response/MyPageResponse.java
  src/main/java/com/example/appjambackend/domain/user/service/MyPageService.java
  src/main/java/com/example/appjambackend/global/config/S3Config.java
  src/main/java/com/example/appjambackend/global/error/exception/ErrorCode.java
  src/main/java/com/example/appjambackend/global/util/s3/S3Service.java
Labels: 기능 추가, 리펙토링

#37 🔀 :: Feed이미지
  src/main/java/com/example/appjambackend/domain/feed/presentation/dto/response/FeedResponse.java
  src/main/java/com/example/appjambackend/domain/feed/service/ModifyFeedService.java
  src/main/java/com/example/appjambackend/domain/feed/service/RemoveFeedService.java
  src/main/java/com/example/appjambackend/domain/image/entity/ImageRepository.java
  src/main/java/com/example/appjambackend/domain/image/facade/ImageFacade.java
Labels: 리펙토링
